[package]
name = "blockchat"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "node"
path = "src/bin/node.rs"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
rsa = { version = "0.9.6", features = ["serde", "sha2"] }
rand = "0.8.5"

[profile.dev.package.num-bigint-dig]
opt-level = 3